<a href="https://colab.research.google.com/github/kit1412/basicprojects/blob/pythoncodes/Assignment08_31_10_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. For a given n by n square matrix, write a program for summing the principal and non- principal diagonal elements.

In [ ]:
import numpy as np
import math

n = int(input("Input the size of the matrix\n"))
#getting the size from the user

y = np.random.randint(10, 99, (n, n))
#generating a random matrix of size 5 * 5

print("The generated random matrix = \n", y)

print("The sum of the principal diagonal elements = ", np.trace(y))
#we can find the trace of the matrix to find the sum of the diagonal elements

print("The sum of the non-principal diagonal elements = ", np.trace(np.fliplr(y)))
#we can flip the matrix to obtain the sum of the non-diagonal elements of the original

Input the size of the matrix
8
The generated random matrix = 
 [[27 70 23 21 49 70 53 30]
 [69 89 32 77 50 87 13 45]
 [14 53 43 67 52 96 92 27]
 [17 72 84 56 66 41 84 65]
 [90 60 39 38 31 73 14 54]
 [28 14 98 52 74 46 25 84]
 [56 80 57 65 30 73 47 68]
 [88 41 49 66 93 61 14 87]]
The sum of the principal diagonal elements =  426
The sum of the non-principal diagonal elements =  509


2. Create a list of 10 students and 6 subjects, and generate random marks between 0 and 100 for each student for all subjects. Create a menu driven program to find out and display:
i) Students with highest and lowest total marks
ii) Subjects with the highest and lowest average score
iii) Students with the highest score in each subject


In [ ]:
import numpy as np
import pandas as pd

#the given matrix should have 10 rows and 6 columns

mat = np.random.randint(0, 100, (10, 6))
print("The randomly generated matrix = \n", mat)

rows = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]
cols = ["Sub 1", "Sub 2", "Sub 3", "Sub 4", "Sub 5", "Sub 6"]

#the sum of each row will give the maximum marks for each student, and the sum of each column that for each subject

student = np.array(np.sum(mat, axis = 1))
marks = np.array(np.mean(mat, axis = 0))

m = pd.DataFrame(data = mat, index = rows, columns = cols)

m['Total'] = student
#adding the individual marks of students as an extra column

mark = np.append(marks, 0)
#print(marks)
#have to store it separately as we will perform max and min operations afterward

size = len(m)
m.loc['Average'] = mark
#adding the total marks for each subject as a row

print("\n\nThe organized data = \n", m)
#print("\n\nThe individual total marks of students = ", student)
#print("The total marks for each subject = ", marks)

#the dataframe is purely for the purpose of a comprehensive display and is not used anywhere in the rest of the program, which is based on numpy alone

ch = -1

while (ch != 0):
  print("\n\nMenu:")
  print("1 - To print the students with the highest and the lowest marks")
  print("2 - To print the subjects with the highest and lowest average marks")
  print("3 - To print the students who scored best in each subject")
  print("0 - Quit")

  ch = int(input("\nInput your choice\t"))

  if ch == 1:
    print("The student with the highest total marks is ", rows[np.argmax(student)], end = "")
    print("  with marks = ", np.max(student))
    print("The student with the lowest total marks is ", rows[np.argmin(student)], end = "")
    print("  with marks = ", np.min(student))
  elif ch == 2:
    print("The subject with the highest average score is ", cols[np.argmax(marks)], end = "")
    print("  with marks = ", np.max(marks))
    print("The subject with the lowest average score is ", cols[np.argmin(marks)], end = "")
    print("  with marks = ", np.min(marks))
  elif ch == 3:
    for i in range(0, 6):
      ele = np.max(mat[:,i])
      ind = np.argmax(mat[:, i]) #we are obtaining the index of each row which has the largest marks
      #print(ind)
      print(rows[ind], " ", end = "")
      print("has the highest marks in", cols[i], end = "")
      print(" with marks ", ele)
  elif ch == 0:
    print("\n\nEnd of program!!")      
  else:
    print("\nIncorrect option")  

The randomly generated matrix = 
 [[78 42 93 92 28 68]
 [74 63  0 17 81 67]
 [53 49 97 68 79 14]
 [65 13 62 11 49 53]
 [48 32 64 75 76 17]
 [86 43 82 28  9 66]
 [61  8 33 68 20  1]
 [80 42 56  5 64 89]
 [77 23 43 54 45 40]
 [91 58 71 57  4 20]]


The organized data = 
          Sub 1  Sub 2  Sub 3  Sub 4  Sub 5  Sub 6  Total
A         78.0   42.0   93.0   92.0   28.0   68.0  401.0
B         74.0   63.0    0.0   17.0   81.0   67.0  302.0
C         53.0   49.0   97.0   68.0   79.0   14.0  360.0
D         65.0   13.0   62.0   11.0   49.0   53.0  253.0
E         48.0   32.0   64.0   75.0   76.0   17.0  312.0
F         86.0   43.0   82.0   28.0    9.0   66.0  314.0
G         61.0    8.0   33.0   68.0   20.0    1.0  191.0
H         80.0   42.0   56.0    5.0   64.0   89.0  336.0
I         77.0   23.0   43.0   54.0   45.0   40.0  282.0
J         91.0   58.0   71.0   57.0    4.0   20.0  301.0
Average   71.3   37.3   60.1   47.5   45.5   43.5    0.0


Menu:
1 - To print the students with the hig


3. A=np.array([[17, 24, 1, 8, 15], [23, 5, 7, 14, 16], [ 4, 6, 13, 20, 22], [10, 12, 19, 21, 3], [11, 18, 25, 2, 9]]). Verify whether array A is a magic square.


In [ ]:
import numpy as np

A = np.array([[17, 24, 1, 8, 15], [23, 5, 7, 14, 16], [ 4, 6, 13, 20, 22], [10, 12, 19, 21, 3], [11, 18, 25, 2, 9]])

flag = 0
#if the value of this variable is 0 at the end of it all, then the matrix is a magic square

rows = np.array(np.sum(A, axis = 1))
cols = np.array(np.sum(A, axis = 0))

if np.min(rows) != np.max(rows) or np.min(cols) != np.max(cols): #if the maximum of an array is equal to the minimum then all the elements are equal
  flag = 1
else:  
  s = np.min(rows)
  if np.trace(A) == s and np.trace(np.fliplr(A)) == s: #on flipping we can find the trace to obtain the sum of non-principal diagonal elements
    print("It is a magic square")  
  else:
    flag = 1  

if flag == 1:
  print("It is not a magic square")

It is a magic square


4. Create an n dimensional array with random elements from 0 to 10. Count how many even indices have odd elements and how many odd indices have even elements.

In [ ]:
import numpy as np

n = int(input("Input the value of n \t"))

a = np.random.randint(0, 10, n)
print(a)

odind = np.array(a[1::2])
evind = np.array(a[::2])
#separating the elements with odd and even indices

odind = odind % 2 == 0
evind = evind % 2 == 1
#storing in a boolean numpy array

print("No of elements in odd indices which are even = ", np.count_nonzero(odind))
print("No of elements in even indices which are odd = ", np.count_nonzero(evind))
#these functions return the number of True values in the boolean array

Input the value of n 	9
[2 1 9 3 4 5 3 9 7]
No of elements in odd indices which are even =  0
No of elements in even indices which are odd =  3


5. Based on the dataset car_sales.xlsx, automobile company Hyundai sells three different cars A, B and C which consists of the monthly sales of each car in the year 2019 from 3 different locations. From the dataset answer the following questions.
a. Create a 3D Numpy array for this data. The dimensions are Months of the year, No. of Cars, and the locations.
b. Find the quarterly sales figures for each car model.
c.  Find the average quarterly sales of car A(in the first quarter), car B(in the second quarter) and car C(in the third quarter)
d.  In terms of the annual sales, sort the product on the basis of their popularity.
e.  Based on the first half of the year, which of the 2 cars have more similarity in terms of their monthly sales.
(Hint: Use Euclidean distance)


In [ ]:
import pandas as pd
import numpy as np
import math


loc1 = pd.read_excel("car_sales.xlsx", "Location 1")
loc2 = pd.read_excel("car_sales.xlsx", "Location 2")
loc3 = pd.read_excel("car_sales.xlsx", "Location 3")
#the data from the three sheets in the book is stored here

sales = np.zeros((3, len(loc1), 3))
#sales[0, 0, 0] = loc1.to_numpy()

loc1 = loc1[loc1.columns[1:4]].to_numpy()
loc2 = loc2[loc2.columns[1:4]].to_numpy()
loc3 = loc3[loc3.columns[1:4]].to_numpy()

sales[0] = loc1
sales[1] = loc2
sales[2] = loc3
#stored all three values in the array

#print(sales)

#to find the quarterly sales for each car model - found for each location and also for all the locations

cars = ['A', 'B', 'C']
location = ['1', '2', '3']

quarterly = np.zeros(12)
k = 0

for i in range(0, 3):
    print("For car ", cars[i])
    for j in range(0, 3): 
      print("At location ", location [j])
      #print(k)
      print("First quarterly sales = ", sales[j, 0, i] + sales[j, 1, i] + sales[j, 2, i], end = "\t")
      quarterly[k] += sales[j, 0, i] + sales[j, 1, i] + sales[j, 2, i]
      print("Second quarterly sales = ", sales[j, 3, i] + sales[j, 4, i] + sales[j, 5, i], end = "\t")
      quarterly[k + 1] += sales[j, 3, i] + sales[j, 4, i] + sales[j, 5, i]
      print("Third quarterly sales = ", sales[j, 6, i] + sales[j, 7, i] + sales[j, 8, i], end = "\t")
      quarterly[k + 2] += sales[j, 6, i] + sales[j, 7, i] + sales[j, 8, i]
      print("Fourth quarterly sales = ", sales[j, 9, i] + sales[j, 10, i] + sales[j, 11, i])
      quarterly[k + 3] += sales[j, 9, i] + sales[j, 10, i] + sales[j, 11, i]
    print("\n")

    print("For car ", cars[i])
    print("The total first quarterly sales (considering all the locations) = ", quarterly[k])  
    print("The total second quarterly sales (considering all the locations) = ", quarterly[k + 1])
    print("The total third quarterly sales (considering all the locations) = ", quarterly[k + 2])
    print("The total fourth quarterly sales (considering all the locations) = ", quarterly[k + 3])
    print("\n")

    k += 4


#average quaterly sales

#we have the total quarterly sales stored in the quarterly[] array of 12 elements, four quarters of each car in order, across all 3 locations

print("The average first quarterly sales for A = ", quarterly[0]/9.0)
print("The average second quarterly sales for B = ", quarterly[5]/9.0)
print("The average third quarterly sales for C = ", quarterly[10]/9.0)

#to find out which car is most popular in terms of its annual sales

print("\n\n")


#for the last two parts, the sales across all the three locations has been considered

k = 0
popular = np.zeros(3)
for i in range(0, 3):
  popular[i] = quarterly[k] + quarterly[k + 1] + quarterly[k + 2] + quarterly[k + 3]
  k += 4
  print("The annual sales for car", cars[i], end = "")
  print(" is ", popular[i])  

print("The cars in their increasing order of popularity = ", cars[np.argmin(popular)], cars[np.argsort(popular)[len(popular)//2]], cars[np.argmax(popular)])

print("\n\n")

#to find out using euclidean distance which of the two cars are more similar in terms of their monthly sales

cars = ["A and B", "B and C", "C and A"]

diff = np.zeros(3)

#initializing varialbles and creating a numpy array with zeroes of size 3

for i in range(0, 3): #to keep track of the cars
  if i == 2:
    a = 0
  else:
    a = i + 1 
  for j in range(0, 6):#to keep track of the rows 
      p1 = sales[0, j, i] + sales[1, j, i] + sales[2, j, i]
      p2 = sales[0, j, a] + sales[1, j, a] + sales[2, j, a] #as the formula is (x1 - x2)^2, and x1, x2 are the total sales for a month for the respective cars
      #print("p1 = ", p1)
      #print("p2 = ", p2)
      diff[i] += math.pow(p1-p2, 2)
      #print(diff[i])
  diff[i] = math.sqrt(abs(diff[i]))      
  #since we are dealing with squares, the values will be different if we consider 3 * value of one sheet and summation of all three while squaring - this is to generalize the program6
#we will get 1/3 this value if we square for each sale, but we are finding the difference it is all proportional and thus we can accurately determine
#as we have to consider the euclidean distance between the sales of each month, the three locations are combined and squared
#at the very end, the square root is applied on the absolute difference of these values  

print("The Euclidean distances are:")
for i in range(0, 3):
  print("For ", cars[i], end = " ")
  print(" the difference is ", diff[i])


print("The most similar sales are for ", cars[np.argmin(diff)])      

For car  A
At location  1
First quarterly sales =  7352.0	Second quarterly sales =  8587.0	Third quarterly sales =  8349.0	Fourth quarterly sales =  6966.0
At location  2
First quarterly sales =  7352.0	Second quarterly sales =  8587.0	Third quarterly sales =  8349.0	Fourth quarterly sales =  6966.0
At location  3
First quarterly sales =  7352.0	Second quarterly sales =  8587.0	Third quarterly sales =  8349.0	Fourth quarterly sales =  6966.0


For car  A
The total first quarterly sales (considering all the locations) =  22056.0
The total second quarterly sales (considering all the locations) =  25761.0
The total third quarterly sales (considering all the locations) =  25047.0
The total fourth quarterly sales (considering all the locations) =  20898.0


For car  B
At location  1
First quarterly sales =  7064.0	Second quarterly sales =  9827.0	Third quarterly sales =  7598.0	Fourth quarterly sales =  8947.0
At location  2
First quarterly sales =  7064.0	Second quarterly sales =  9827.0	T